[package]
name = "task-tracker-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
colored = "2.1.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"

[dev-dependencies]
tempfile = "3.14.0"
